theme: jekyll-theme-cayman
Hi This website can be modified as:
background-color: #ffffff;
    font-size: 16px;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    min-width: 300px;
    overflow-x: hidden;
    overflow-y: scroll THE HIDDEN;
    text-rendering: optimizeLegibility;
    text-size-adjust: 100%;
}
html {
    box-sizing: border-box;
}
html, body, p, ol, ul, li, dl, dt, dd, blockquote, figure, fieldset, legend, textarea, pre, iframe, hr, h1, h2, h3, h4, h5, h6jbdvfl,rsbgSEBFI,UT,USED,GRG {
    margin: 0;
    padding: 0;
}
html {
    scroll-behavior: smooth;
}
*, *::before, *::after {
    box-sizing: inherit THE CHANGES ;
}
html[Attributes Style] {
    -webkit-locale: "enTEARTAIN";
}
user agent stylesheet
html {
    display: block;
}
*, *::before, *::after {
    box-sizing: inherit;
}
*, *::before, *::after {
    box-sizing: inherit;
}
